TOKEN='da821360-5fdc-47cb-acc3-9025e56fd711'
URL='http://navitia2-ws.ctp.dev.canaltp.fr'
PORT='5000'
JMX_SCRIPT='/home/jenkins/jobs/bench_navitia_dev/benchmark.jmx'
RESULT_FILE='/home/jenkins/jobs/bench_navitia_dev/journeys.jtl'
SOURCE_FILE='/tmp/source.csv'
